version: "3.7"

networks:
  my-net:
    external: true
    name: my-net

services:
  nginx:
    image: nginx:1.19-alpine
    restart: always
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      my-net: {}
